config/routes.rb
Throwback::Application.routes.draw do
  
  
  root :to => "welcome#index"

  match 'reports/:pitcher_id/pitcher_performance' => 'report#pitcher_performance', :as => 'pitcher_report'
  match 'reports/:pitcher_id/pitches_per_game' => 'report#pitches_per_game', :as => 'pitches_per_game'
  match 'reports/:pitcher_id/pitcher_performance/:game_id' => 'report#pitcher_performance_game', :as => 'pitcher_game_report'
  match 'reports/:pitcher_id/pitcher_performance/:game_id/velocity' => 'report#velocity_data', :as => 'pitcher_game_velocity'
  resources :pitchers, :only => [:index, :show]

end

app/models/batter.rb
class Batter < ActiveRecord::Base
  self.primary_key = 'batter_id'
  attr_accessible :batter_id, :first_name, :last_name
end

app/models/game.rb
class Game < ActiveRecord::Base
  self.primary_key = 'game_id'
  attr_accessible :game_id, :game_date
  # attr_accessible :title, :body
end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
  belongs_to :pitcher
  belongs_to :game
  belongs_to :batter
  belongs_to :pitch_result, :foreign_key => 'pitch_result_code', :primary_key => 'code'
  attr_accessible *column_names
  
  def self.strikes
    Pitch.joins(:pitch_result).where(:pitch_results => {:strike => true, :contact => false} )
  end
  
  def self.balls
    Pitch.joins(:pitch_result).where(:pitch_results => {:strike => false, :swinging => false})
  end
  
  def self.hits
    Pitch.joins(:pitch_result).where(:pitch_results => {:in_play => true, :out => false} )
  end
  
  def self.vs_left
    where(:batter_stance => 'L')
  end
  
  def self.vs_right
    where(:batter_stance => 'R')
  end
  
end

app/models/pitch_result.rb
class PitchResult < ActiveRecord::Base
  # attr_accessible :title, :body
  self.primary_key = 'code'
  attr_accessible *column_names
  def self.from_csv_row(csv)
    exclude_columns = ['created_at', 'updated_at']
    col_names = column_names.delete_if{|col| exclude_columns.include?(col)}
    attrs = {}
    col_names.each do |col|
      attrs[col] = csv[col]
    end
    new(attrs)
  end
end

app/models/pitcher.rb
class Pitcher < ActiveRecord::Base
  self.primary_key = 'pitcher_id'
  has_many :pitches
  
  attr_accessible :pitcher_id, :throws, :first_name, :last_name
  
  # #distinct and #uniq seem to be broken in this version of rails
  #see https://github.com/rails/rails/issues/7399
  #so work around with raw sql
  #in a prod environment I'd try upgrading Rails to 4, not sure I have time at the moment
  def distinct_games
    Game.find_by_sql(["select distinct game_id from pitches where pitcher_id = ? order by game_id asc", pitcher_id]).map(&:game_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :create_title_variable
  
  private
  def create_title_variable
    @title = 'Throwback'
  end
end

app/controllers/pitchers_controller.rb
class PitchersController < ApplicationController
  def index
    if (params["search"])
      search_term = params["search"] + '%'
      @pitchers = Pitcher.where('pitcher_id like ? or first_name like ? or last_name like ?',
        search_term, search_term, search_term).order("pitcher_id").paginate(:page => params[:page])
    else
      @pitchers = Pitcher.order("pitcher_id").paginate(:page => params[:page])
    end
  end
  
  def show
    @pitcher = Pitcher.find(params[:id])
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  include ReportHelper
  def pitcher_performance
    @pitcher = Pitcher.where(:pitcher_id => params[:pitcher_id]).first
    @pitcher_game_ids = @pitcher.pitches.group(:game_id).count.keys
    @pitcher_pitches_per_game = @pitcher.pitches.group(:game_id).count.values
    @pitches = Pitch.where(:pitcher_id => params[:pitcher_id])
    @title = "#{@title} - Career report for #{@pitcher.first_name} #{@pitcher.last_name}"
  end
  
  def pitcher_performance_game
    @pitcher = Pitcher.where(:pitcher_id => params[:pitcher_id]).first
    @game = Game.where(:game_id => params[:game_id]).first
    @pitches = Pitch.where(:pitcher_id => params[:pitcher_id],:game_id => params[:game_id] ).order(:pitch_per_game)
    @pitch_rollup = pitch_rollup(@pitches)
    
    @title = "#{@title} - Game #{@game.game_id} report for #{@pitcher.first_name} #{@pitcher.last_name}"

  end
  
  def velocity_data
    pitches = Pitch.where(:pitcher_id => params[:pitcher_id],
      :game_id => params[:game_id] ).order(:pitch_per_game).map{|x| [x.pitch_type,x.pitch_initial_speed,x.pitch_per_game ]}
    pitcher = Pitcher.find params[:pitcher_id]
    game = Game.find params[:game_id]
    response = {:pitches => pitches, :pitcher => pitcher, :game => game}
    respond_to do |format|
      format.js {  render :json => response}
      format.json {render :json => response}
    end
  end
  
  def pitches_per_game
    pitcher = Pitcher.where(:pitcher_id => params[:pitcher_id]).first
    pitches = pitcher.pitches.group(:game_id).count
    game_array = []
    pitches.each_pair do |k, v|
      game_array << {name: k, y: v, url: pitcher_game_report_url(pitcher.pitcher_id, k) }
    end
    response = {games: game_array, pitcher: pitcher}
    respond_to do |format|
      format.js {  render :json => response}
      format.json {render :json => response}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pitcher_helper.rb
module PitcherHelper
end

app/helpers/report_helper.rb
#  <td>Pitch Type</td>
#  <td>Avg. Velocity</td>
#  <td>Max Velocity</td>
#  <td>Horizontal break</td>
#  <td>Count</td>
#  <td>Strikes (pct)</td>
#  <td>Swings (pct)</td>
#  <td>Whiffs (pct)</td>
#  <td>In play, no out</td>
module ReportHelper
  def pitch_rollup(pitches)
    
    group_by_type = pitches.group(:pitch_type)
    avg_velocity_hash = {:name => :average_velocity, :data => group_by_type.average(:pitch_initial_speed)}
    max_velocity_hash = {:name => :max_velocity, :data => group_by_type.maximum(:pitch_initial_speed)}
    horizontal_break_hash = {:name => :horiz_break, :data => group_by_type.average(:pitch_deflection_break_x)}
    count_hash = {:name => :pitch_type_count, :data => group_by_type.count}
    strike_count_hash = {:name => :strike_count, :data => group_by_type.joins(:pitch_result).where(
      :pitch_results => {:strike => true}).count}
    swing_count_hash = {:name => :swing_count, :data => group_by_type.joins(:pitch_result).where(
      :pitch_results => {:swinging => true}).count}
    whiff_count_hash = {:name => :whiff_count, :data => group_by_type.joins(:pitch_result).where(
      :pitch_results => {:contact => false, :swinging => true}).count}
    in_play_no_out_hash = {:name => :ipno, :data => group_by_type.joins(:pitch_result).where(
      :pitch_results => {:in_play => true, :out => false }).count}

    all_hashes = [avg_velocity_hash, max_velocity_hash, horizontal_break_hash, count_hash, 
        strike_count_hash, swing_count_hash, whiff_count_hash, in_play_no_out_hash]
    
    retval = []
    group_by_type.count.keys.each do |type|
      rollup = {}
      rollup[:type] = type

      all_hashes.each do |hash|
        rollup_key = hash[:name]
        if (hash[:data][type] != nil)
          rollup[rollup_key] = hash[:data][type]#.to_s
        else
          rollup[rollup_key] = 0
        end
      end
      retval << rollup        
    end

    retval
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'  %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie'  %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title.blank? ? 'Throwback' : @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "highcharts" %>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <section class="round">
    <%= yield %>
    </section>
  </div>
</body>
</html>

app/views/pitchers/_pitcher.html.erb
<tr>
  <td><%= pitcher.pitcher_id   %></td>
  <td><%= "#{pitcher.first_name} #{pitcher.last_name}" %></td>
  <td><%= pitcher.throws %></td>
  <td><%= link_to 'Career', pitcher_report_path(pitcher)  %></td>
  <td><%= link_to 'Show games', pitcher_path(pitcher)  %></td>
  
</tr>

app/views/pitchers/_search_form.html.erb
<div class="searchform">
  <%= form_tag pitchers_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], :placeholder => "Name or ID" %>
    <%= submit_tag "Find pitcher", :name => nil %>
  </p>
  <% end %>
</div>

app/views/pitchers/index.html.erb
<h1>All pitchers</h1>
<%= render 'search_form' %>
<%= will_paginate  %>
<table class="pitchers">
  <thead>
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Throws</td>
      <td>Career report</td>
      <td>Link to Games</td>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "pitcher", :collection => @pitchers %>
  </tbody>
</table>

<%= will_paginate %>
<% if params['search'] %>
<%= link_to 'Back to index', pitchers_path %>
<% end %>

app/views/pitchers/show.html.erb
<table>
  <thead>
  <td><%= @pitcher.pitcher_id %> </td>
  <td><%= "#{@pitcher.first_name} #{@pitcher.last_name}" %></td>
  </thead>
</table>

<table id="games">
  <% @pitcher.distinct_games.each do |game| %>
  <tr>
  <td><%= link_to "Performance for game #{game}", pitcher_game_report_path(@pitcher, game) %></td>
  </tr>
  <% end %>
</table>

app/views/report/_pitch_breakdown.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= pie_chart @pitches.group(:pitch_type).order(:pitch_type).count %>

app/views/report/_pitch_statistics.html.erb
<!--  <td>Pitch Type</td>
  <td>Avg. Velocity</td>
  <td>Max Velocity</td>
  <td>Horizontal break</td>
  <td>Count</td>
  <td>Strikes (pct)</td>
  <td>Swings (pct)</td>
  <td>Whiffs (pct)</td>
  <td>In play, no out</td> -->
<% percentage_format_string = "%2.1f%" %>
<tr>
  <td><%= line[:type] %></td>
  <td><%= "%0.02f" % line[:average_velocity] %></td>
  <td><%= line[:max_velocity] %></td>
  <td><%= "%0.02f" % line[:horiz_break] %></td>
  <td><%= line[:pitch_type_count] %></td>
  <td><%= line[:strike_count] %>(<%= percentage_format_string % (100 * (line[:strike_count]/line[:pitch_type_count].to_f))  %>)</td>
  <td><%= line[:swing_count] %>(<%= percentage_format_string % (100 *(line[:swing_count]/line[:pitch_type_count].to_f))  %>)</td>
  <td><%= line[:whiff_count] %>(<%= percentage_format_string % (100*(line[:whiff_count]/line[:pitch_type_count].to_f))  %>)</td>
  <td><%= line[:ipno] %></td>
</tr>

app/views/report/_pitches_per_game.html.erb
<script type="text/javascript">
  
  var chart;
  function requestData() {
    $.ajax({
        url: '<%= pitches_per_game_url(params[:pitcher_id])%>',
        dataType: 'json',
        success: function(response) {
            data = response;
            title = "Pitches per game for " + data.pitcher.first_name + " " + data.pitcher.last_name;
            subtitle = "(click on a point to go to game specific report)";
            chart.setTitle({text: title}, {text: subtitle}) ;
            chart.series[0].setData(data.games );            
        },
        error: function(request, status, error) {
          alert("Error");
        },
        complete: function() {
        },
        cache: false
    });
}
  $('#tabs').on('tabsactivate', function (event, ui) {
    if (ui.newPanel.is($('#tabs-2'))) {
      chart = new Highcharts.Chart({
          chart: {
              renderTo: 'pitches_per_game_chart',
              events: {
                load: requestData
              },
              zoomType: 'x',
              type: 'line'
          },
          title: {
              
          },
          xAxis: {
              type: 'category'
          },
          yAxis: {
              title: {
                  text: 'Pitches'
              }
          },
          series: [{
              name: 'Pitches',
              events: {
                click: function(event) {
                  window.location = event.point.url;
                  //console.log(event.point)
                }
              },
              data: []
          }]
      });
   }
});
</script>

<div id="pitches_per_game_chart">
  
</div>

app/views/report/_pitches_per_game.js.erb
google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Game', 'Pitches'],
          <% @pitches.group(:game_id).count.each do |k| %>
          <%= "#{k}" %>
          <% end %>
        ]);

        var options = {
          title: 'Company Performance'
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

        chart.draw(data, options);
      }

app/views/report/_velocity_chart.html.erb
<script type="text/javascript">
  var chart;
  function requestData() {
    $.ajax({
        url: '<%= pitcher_game_velocity_url(params[:pitcher_id], params[:game_id])%>',
        dataType: 'json',
        success: function(response) {
            data = response;
            title = "Pitch velocity for " + data.pitcher.first_name + " " + data.pitcher.last_name
            subtitle = data.game.game_id + " on " + data.game.game_date
            chart.setTitle({text: title}, {text: subtitle});
            chart.series[0].setData(data.pitches );            
        },
        error: function(request, status, error) {
          alert("Error");
        },
        complete: function() {
        },
        cache: false
    });
}
  $('#tabs').on('tabsactivate', function (event, ui) {
    if (ui.newPanel.is($('#tabs-2'))) {
      chart = new Highcharts.Chart({
          chart: {
              renderTo: 'velocity_chart',
              zoomType: 'x',
              events: {
                load: requestData
              }
          },
          xAxis: {
              //type: 'category'
          },
          yAxis: {
              title: {
                  text: 'MPH'
              }
          },
          series: [{
              name: 'Velocity',
              data: []
          }]
      });
    }
});
</script>

<div id="velocity_chart"></div>

app/views/report/pitcher_performance.html.erb
<h1><%= "#{@pitcher.pitcher_id} - #{@pitcher.first_name} #{@pitcher.last_name}" %> Career charts</h1>
<script>
   $(function() {
$( "#tabs" ).tabs();
});
</script>

<div id="tabs">
<ul>
<li><a href="#tabs-1">Pitch Breakdown</a></li>
<li><a href="#tabs-2">Pitches Per Game</a></li>
</ul>
<div id="tabs-1">
  <%=  render 'pitch_breakdown' %>
</div>
<div id="tabs-2">
<%=  render 'pitches_per_game' %>
</div>

</div>

<p><%= link_to "Back to pitchers", pitchers_path %></p>
<p><%= link_to "Games list for #{@pitcher.first_name} #{@pitcher.last_name}", pitcher_path(@pitcher) %></p>

app/views/report/pitcher_performance_game.html.erb
<h1><%= "#{@pitcher.pitcher_id} - #{@pitcher.first_name} #{@pitcher.last_name}" %> performance in game <%=@game.game_id %></h1>
<script>
   $(function() {
$( "#tabs" ).tabs();
});
</script>

<div id="tabs">
<ul>
<li><a href="#tabs-1">Pitch choice</a></li>
<li><a href="#tabs-2">Velocity chart</a></li>
<li><a href="#tabs-3">Pitch Statistics</a>
</ul>
<div id="tabs-1">
  <%=  render 'pitch_breakdown' %>
</div>
<div id="tabs-2">
<%=  render 'velocity_chart' %>
</div>
<div id="tabs-3">
  <table id="rollup_report" class="rollup_report">
  <thead>
    <tr>
    <th>Pitch Type</th>
    <th>Avg. Velocity</th>
    <th>Max Velocity</th>
    <th>Avg. horizontal break</th>
    <th>Count</th>
    <th>Strikes (pct)</th>
    <th>Swings (pct)</th>
    <th>Whiffs (pct)</th>
    <th>In play, no out</th>
  </thead>
  <tbody>
    <%= render :partial => 'pitch_statistics', :collection => @pitch_rollup, :as => :line %>
  </tbody>
</table>
</div> 

     

</div>

<%= link_to "Back to pitchers", pitchers_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Throwback</h1>

<p>Throwback displays charts and graphs to aid in pitcher analysis.</p>
<p>Head to the <%= link_to 'pitchers page', pitchers_path %> to see the pitchers.</p>